### ISSUE TITLE
module 'browserify-sha3' missing after installation

### ISSUE THREAD

**Issue by koeppelmann** [blockapps/bloc#120]
I tried to install bloc. Did the npm install -g and it went through without errors.
However, when I did a bloc init I got:

``` module.js:329
    throw err;
    ^

Error: Cannot find module 'browserify-sha3'
    at Function.Module._resolveFilename (module.js:327:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockapps-bloc/node_modules/ethereumjs-util/index.js:1:14)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/blockapps-bloc/node_modules/ethereumjs-tx/index.js:1:17)
    at Module._compile (module.js:399:26)
    at Object.Module._extensions..js (module.js:406:10)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
```

**Comment by kjameslubin** [comment]
For some reason you need to `npm install -g browserify-sha3`.

**Comment by koeppelmann** [comment]
Thanks - worked.
