### ISSUE TITLE
As a user, generate key, so i can compile and upload

### ISSUE THREAD

**Issue by liorsaar1** [blockapps/bloc#130]
random timeouts during genkey (works 50%)

`$ sudo bloc genkey`

prompt: Enter a high entropy password. You will need this to sign transactions.:  
wrote app/users/admin/e78eee59c7d6078815e6e0b1642f7c3dbe3210e7.json
Unhandled rejection Error: faucet: waited 10 seconds
    at Object.ensureErrorObject (/usr/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:469:22)
    at Promise._settlePromiseFromHandler (/usr/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:513:17)
    at Promise._settlePromiseAt (/usr/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/usr/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/usr/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:15:14)
    at tryOnImmediate (timers.js:534:15)
    at processImmediate [as _immediateCallback] (timers.js:514:5)

**Comment by kejace** [comment]
This depends on the blocktime. We should make the timeout a configuration parameter.
