### ISSUE TITLE
bloc register should work outside directory?

### ISSUE THREAD

**Issue by kejace** [blockapps/bloc#16]
It is easy to forget to `cd` into myproject.

Right now `bloc` fails like this
```
➜  bloc register
fs.js:565
fs.write = function(fd, buffer, offset, length, position, callback) {
                                                 ^
Error: ENOENT, no such file or directory 'config.yaml'
    at Error (native)
    at Object.fs.openSync (fs.js:500:18)
    at Object.fs.readFileSync (fs.js:352:15)
    at Object.readYaml (/home/kejace/npm/lib/node_modules/bloc/lib/yaml-config.js:26:27)
    at main (/home/kejace/npm/lib/node_modules/bloc/bin/main.js:43:29)
    at Object.<anonymous> (/home/kejace/npm/lib/node_modules/bloc/bin/main.js:157:5)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

I suggest we make a nice error message here and/or support
```bloc register myproject```
for user friendliness

**Comment by kjameslubin** [comment]
Maybe one of those standard "cd myproject && bloc register" statements afterward? You don't actually have to register anymore, btw, because of developer mode. Perhaps "cd myproject && bloc"

**Comment by kejace** [comment]
Agreed. Probably we should just hint it with the tool. The current error
message kind of makes it looks like `bloc` is broken.

Something like `if(!config.yaml){ print("Did you forget to cd myproject?")}
else { do something }`
