### ISSUE TITLE
Unhandled rejection Error: faucet: HTTPQuery: undefined is not a function

### ISSUE THREAD

**Issue by tenny1225** [blockapps/bloc#181]
Hi!
When I use `bloc genkey`, the following error occurred

How can I fix this error?
Thanks!
> Unhandled rejection Error: faucet: HTTPQuery: undefined is not a function
    at Object.ensureErrorObject (c:\Users\Administrator\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\util.js:261:20)
    at Promise._rejectCallback (c:\Users\Administrator\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:469:22)
    at Promise._settlePromiseFromHandler (c:\Users\Administrator\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:513:17)
    at Promise._settlePromiseAt (c:\Users\Administrator\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (c:\Users\Administrator\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (c:\Users\Administrator\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\Users\Administrator\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\Users\Administrator\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)

**Comment by andkler** [comment]
Also having this problem. Has anyone found a workaround or a way of fixing this? Thanks
