### ISSUE TITLE
Bloc start does not start web server

### ISSUE THREAD

**Issue by joshterrill** [blockapps/bloc#185]
I found this guide written by consensys and am following it to compile contracts in visual studio: https://medium.com/@ConsenSys/solidity-integration-with-visual-studio-8bdab2ff8a74#.xq639ss3w

Part of the tutorial says to do `bloc init`, then `cd` into your project and run `bloc start`. According to the article, I should see a response saying that a server has started on port 8000, however I do not see any response. I type in `bloc start` and nothing happens, just a blank line in the console. I tried to go to `http://localhost:8000` and even `http://localhost:3000` because I saw a reference to that port in the current readme of bloc. But neither of those addresses go to any web server.

Here's some info about what I'm running:
OS: Windows 10 VM running on Macbook Pro (via Parallels)
Node Version: 5.7.0
NPM Version: 3.5.3

**Comment by jcrain** [comment]
Hey Josh, can you try running `node app.js` instead of `bloc start` and let me know what the output is?

**Comment by joshterrill** [comment]
It throws an error:

```
C:\projects\VSContract1\testapp>node app.js
module.js:341
    throw err;
    ^

Error: Cannot find module './tatus/template'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.require.resolve (internal/module.js:23:19)
    at create (C:\projects\VSContract1\testapp\app\components\contracts\template.marko.js:10:46)
    at Object.Template.c (C:\projects\VSContract1\testapp\node_modules\marko\runtime\marko-runtime.js:103:18)
    at Object.<anonymous> (C:\projects\VSContract1\testapp\app\components\contracts\template.marko.js:37:51)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at loadFile (C:\projects\VSContract1\testapp\node_modules\marko\runtime\loader.js:83:16)
    at load (C:\projects\VSContract1\testapp\node_modules\marko\runtime\loader.js:129:16)
    at Object.load (C:\projects\VSContract1\testapp\node_modules\marko\runtime\marko-runtime.js:295:33)
    at Object.<anonymous> (C:\projects\VSContract1\testapp\app\routes\contract.js:16:41)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (C:\projects\VSContract1\testapp\app.js:10:17)
```

**Comment by vinaychauhan-java** [comment]
Yes, Same is the case with me. After executing bloc start, nothing is happening. Please assist for the same.

**Comment by vinaychauhan-java** [comment]
Following are the steps followed for Resolution:-
**(1) C:\MyApp>node app.js start**
	module.js:341
	throw err;
	^
	Error: Cannot find module './tatus/template'
		at Function.Module._resolveFilename (module.js:339:15)
		at Function.require.resolve (internal/module.js:23:19)
		at create (C:\MyApp\app\components\contracts\template.marko.js:10:46)
		at Object.Template.c (C:\MyApp\node_modules\marko\runtime\marko-runtime.js:103:18)
		at Object.<anonymous> (C:\MyApp\app\components\contracts\template.marko.js:37:51)
**(2) Edit a file :- C:\MyApp\app\components\contracts\template.marko.js**
	...
	...
	___contractFunctionsCall_template = __helpers.l(require.resolve("../contractFunctionsCall/template"));
	//___status_template = __helpers.l(require.resolve("../status/template"));
	...
	...
	//___status_template.render({"contractMeta": data.contractMeta, "apiURL": data.apiURL}, out);
**(3) C:\MyApp>bloc start**
	bloc is listening on http://0.0.0.0:8000
	api is pointed to http://strato-dev4.blockapps.net with profile strato-dev

**Comment by mavlGlobant** [comment]
In case you need it:

I was having the same error, but in my case i got this message:

> C:\Users\mavl\globant\ethertest>bloc start
> 
> C:\Users\mavl\globant\ethertest>node app.js
> module.js:327
>     throw err;
>     ^
> 
> **Error: Cannot find module 'chalk'**
>     at Function.Module._resolveFilename (module.js:325:15)
>     at Function.Module._load (module.js:276:25)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\mavl\globant\ethertest\app\lib\compile.js:5:13)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\mavl\globant\ethertest\app\routes\users.js:35:15)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)
>     at Function.Module._load (module.js:300:12)
>     at Module.require (module.js:353:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (C:\Users\mavl\globant\ethertest\app.js:8:13)
>     at Module._compile (module.js:409:26)
>     at Object.Module._extensions..js (module.js:416:10)
>     at Module.load (module.js:343:32)

**So, to fix it, i installed "chalk"**

> C:\Users\mavl\globant\ethertest>npm install chalk
> npm WARN package.json ethertest@1.0.0 No description
> npm WARN package.json ethertest@1.0.0 No repository field.
> npm WARN package.json ethertest@1.0.0 No README data
> chalk@1.1.3 node_modules\chalk
> ├── escape-string-regexp@1.0.5
> ├── ansi-styles@2.2.1
> ├── supports-color@2.0.0
> ├── strip-ansi@3.0.1 (ansi-regex@2.0.0)
> └── has-ansi@2.0.0 (ansi-regex@2.0.0)

**and Voila!!**

> **C:\Users\mavl\globant\ethertest>node app.js start
> bloc is listening on http://0.0.0.0:8000
> api is pointed to http://strato-dev4.blockapps.net with profile strato-dev
> GET / 200 6.855 ms - 10
> GET /favicon.ico 404 85.528 ms - 24**
> 
Hope some one helps.

**Comment by meghana87** [comment]
Hi all,

I'm getting the below error when running 'node app.js start':

/Users/meghanay/Documents/blockchain/myApp/node_modules/property-handlers/lib/index.js:23
                throw cause;
                ^

Error: Error while applying option of "node-class". Cause: TypeError: extensions.hasOwnProperty is not a function
    at /Users/meghanay/Documents/blockchain/myApp/node_modules/raptor-modules/resolver/lib/serverResolveRequire.js:25:32
    at Object.find (/Users/meghanay/Documents/blockchain/myApp/node_modules/raptor-modules/resolver/lib/search-path.js:14:31)
    at serverResolveRequire (/Users/meghanay/Documents/blockchain/myApp/node_modules/raptor-modules/resolver/lib/serverResolveRequire.js:18:29)
    at TagHandlers.nodeClass (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-tag.js:175:20)
    at invokeHandlers (/Users/meghanay/Documents/blockchain/myApp/node_modules/property-handlers/lib/index.js:72:29)
    at Object.loadTag (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-tag.js:587:5)
    at handleTag (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-taglib.js:70:32)
    at TaglibHandlers.tags (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-taglib.js:133:17)
    at invokeHandlers (/Users/meghanay/Documents/blockchain/myApp/node_modules/property-handlers/lib/index.js:72:29)
    at Object.exports.loadTaglib (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-taglib.js:280:5)
    at Object.load (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/index.js:31:25)
    at Object.registerTaglib (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-lookup.js:70:31)
    at Object.<anonymous> (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/marko-compiler.js:154:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/runtime/loader.js:21:21)
    at Module._compile (module.js:569:30) (<c-template> tag in /Users/meghanay/Documents/blockchain/myApp/node_modules/marko/taglibs/core/marko-taglib.json)
    at error (/Users/meghanay/Documents/blockchain/myApp/node_modules/property-handlers/lib/index.js:33:17)
    at invokeHandlers (/Users/meghanay/Documents/blockchain/myApp/node_modules/property-handlers/lib/index.js:75:17)
    at Object.loadTag (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-tag.js:587:5)
    at handleTag (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-taglib.js:70:32)
    at TaglibHandlers.tags (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-taglib.js:133:17)
    at invokeHandlers (/Users/meghanay/Documents/blockchain/myApp/node_modules/property-handlers/lib/index.js:72:29)
    at Object.exports.loadTaglib (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/loader-taglib.js:280:5)
    at Object.load (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-loader/index.js:31:25)
    at Object.registerTaglib (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/taglibs/taglib-lookup.js:70:31)
    at Object.<anonymous> (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/compiler/marko-compiler.js:154:17)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/meghanay/Documents/blockchain/myApp/node_modules/marko/runtime/loader.js:21:21)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)

Please can somebody let me understand the issue and a probable fix for this.

Thanks
