### ISSUE TITLE
Error trying to get a key (bloc genkey)

### ISSUE THREAD

**Issue by mavlGlobant** [blockapps/bloc#188]
Hi! when trying to create a new key (bloc genkey) i got this error:

> prompt: Enter a high entropy password. You will need this to sign transactions.:
> wrote app\users\admin\d2efeb725ea71e4bdbd15f48059321087d06709e.json
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
>     ...waiting for transaction to be mined
> **Unhandled rejection Error: faucet: HTTPQuery: connect ETIMEDOUT 13.88.13.192:80
>     at Object.ensureErrorObject (C:\Users\mavl\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\util.js:261:20)
>     at Promise._rejectCallback (C:\Users\mavl\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:472:22)
>     at Promise._settlePromiseFromHandler (C:\Users\mavl\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:516:17)**
> 
>     at Promise._settlePromiseAt (C:\Users\mavl\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:584:18)
>     at Promise._settlePromises (C:\Users\mavl\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:700:14)
>     at Async._drainQueue (C:\Users\mavl\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:123:16)
>     at Async._drainQueues (C:\Users\mavl\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:133:10)
>     at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\mavl\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.
> js:15:14)
>     at processImmediate [as _immediateCallback] (timers.js:383:17)
>     ...waiting for transaction to be mined

It's any workaround?

Thanks in advance.

**Comment by SCLiew-InfoCorp** [comment]
Hi,

I am also currently experiencing this issue on Ubuntu 16 and Windows 10.

Can someone please look into the system or code?

```
prompt: Enter a high entropy password. You will need this to sign transactions.:
wrote app\users\admin\ca65c8159c33ee66cc6bbbf1e8f0f7fb5bb301b2.json
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
Unhandled rejection Error: faucet: waited 10 seconds
    at Object.ensureErrorObject (C:\Users\user\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\util.js:261:20)
    at Promise._rejectCallback (C:\Users\user\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:472:22)
    at Promise._settlePromiseFromHandler (C:\Users\user\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:516:17)
    at Promise._settlePromiseAt (C:\Users\user\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:584:18)
    at Promise._settlePromises (C:\Users\user\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\promise.js:700:14)
    at Async._drainQueue (C:\Users\user\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\Users\user\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues (C:\Users\user\AppData\Roaming\npm\node_modules\blockapps-bloc\node_modules\bluebird\js\main\async.js:15:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
```

**Comment by aditya0711** [comment]
Hi, 
What is your apiURL in the config.yaml file? What profile are you using?

**Comment by SCLiew-InfoCorp** [comment]
Hi Aditya,

This is the default generated config.yaml, I did not edit it.

apiURL: 'http://strato-dev4.blockapps.net'
profile: strato-dev

**Comment by jrmoreau** [comment]
@SCLiew-InfoCorp thanks for your question and @aditya0711 thanks for your attempt to help. Would you mind moving this conversation over to http://forums.blockapps.net/

We're not monitoring this issues repository anymore. Our technical team will see your issues in the forums though and be able to respond.

**Comment by SCLiew-InfoCorp** [comment]
Hi JR,

Have posted the issue there under "Waited 10 seconds…" but did not get a response. 
Ok, will continue from the forums.

Thank you!

**Comment by jrmoreau** [comment]
@SCLiew-InfoCorp thanks for posting on the forums!

**Comment by SCLiew-InfoCorp** [comment]
Thank you for the response too :)

**Comment by MosesSupposes** [comment]
A simple solution for anyone else who stumbles upon this thread:
You can setup a test blockchain network and use that to mine your transaction. Follow these steps:

**1.)** Open up a terminal and type ‘npm install -g testrpc’ .

**2.)** Open config.yaml and under the apiURL key, enter ‘http:// localhost8545’

**3.)** _(Optional)_ In config.yaml under the profile key, enter ‘testrpc’.

**3.)** Type ‘testrpc’ to run the blockchain.

**4.)** In a separate terminal window, cd to your project directory and type ‘bloc genkey’

**5.)** Enter a password.

**6)** Wait .02 seconds and your transaction will be mined )

**Comment by Snorlock** [comment]
👆 didnt work for me :( and it seems you have some typoes in your apiURL suggestion? Or is it suppose to be like that?

**Comment by andreij7** [comment]
I Used @MosesSupposes solution but with replaced step one with this.

1) npm install -g ethereumjs-testrpc
