### ISSUE TITLE
Uploading Greeter error

### ISSUE THREAD

**Issue by rolandkofler** [blockapps/bloc#189]
```
$ bloc upload Greeter
address: 174a421177496da76cb64c46a4af2620351089f5
prompt: Enter password to retrieve private key:  
upload contract: Greeter
there was an error: {"errorTags":["Solidity","Solidity"],"message":"function \"Greeter\" arguments must include \"_greeting\""}
creating metadata for Greeter
Unhandled rejection Error: {"errorTags":["Solidity","Solidity"],"message":"function \"Greeter\" arguments must include \"_greeting\""}
    at Object.ensureErrorObject (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:472:22)
    at Function.Promise.reject.Promise.rejected (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:199:9)
    at /usr/local/lib/node_modules/blockapps-bloc/templates/app/lib/upload.js:55:14
    at tryCatcher (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:574:20)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)

```

**Comment by tmyjoe** [comment]
I think you need to pass an argument for the contract like this.
```
% bloc upload greeter brabra                                   
address: 21df22052a1062ec928206e2f2638095fa2c1dc0
prompt: Enter password to retrieve private key:
upload contract: greeter
writing: app/meta/greeter/f88710278065ea124c9d0fc8f4dfeb74de9981f6.json
writing: app/meta/greeter/Latest.json
creating metadata for greeter
```

**Comment by MajjigaDeepak** [comment]
ubuntu@WBUBUNTU:~/Deepak/projects/bloc/energytradingapp$ sudo bloc upload Greeter
address: b70048b4ae5fba24e5e75391717c6490003c3705
prompt: Enter password to retrieve private key:
upload contract: Greeter
there was an error: {"errorTags":["Solidity","Solidity"],"message":"function \"Greeter\" arguments must include \"_greeting\""}
creating metadata for Greeter
Unhandled rejection Error: {"errorTags":["Solidity","Solidity"],"message":"function \"Greeter\" arguments must include \"_greeting\""}
    at Object.ensureErrorObject (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:472:22)
    at Function.Promise.reject.Promise.rejected (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:199:9)
    at /usr/local/lib/node_modules/blockapps-bloc/templates/app/lib/upload.js:55:14
    at tryCatcher (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
ubuntu@WBUBUNTU:~/Deepak/projects/bloc/energytradingapp$ sudo bloc upload Greeter deepak
address: b70048b4ae5fba24e5e75391717c6490003c3705
prompt: Enter password to retrieve private key:
upload contract: Greeter
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
    ...waiting for transaction to be mined
there was an error: {"errorTags":["submitTransaction","Transaction","Solidity"],"message":"waited 10 seconds"}
creating metadata for Greeter
Unhandled rejection Error: {"errorTags":["submitTransaction","Transaction","Solidity"],"message":"waited 10 seconds"}
    at Object.ensureErrorObject (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/util.js:261:20)
    at Promise._rejectCallback (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:472:22)
    at Function.Promise.reject.Promise.rejected (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:199:9)
    at /usr/local/lib/node_modules/blockapps-bloc/templates/app/lib/upload.js:55:14
    at tryCatcher (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:510:31)
    at Promise._settlePromiseAt (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:584:18)
    at Promise._settlePromises (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/promise.js:700:14)
    at Async._drainQueue (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/blockapps-bloc/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)``
