### ISSUE TITLE
With the default Ubuntu node/npm, bloc install fails, and the message is cryptic....

### ISSUE THREAD

**Issue by jamshidh** [blockapps/bloc#33]
Here is the message

~/bloc> sudo npm install -g
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache/add-named.js:240:24)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:84:10
npm ERR!     at RegClient.get_ (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:130:14)
npm ERR!     at RegClient.<anonymous> (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:49:12)
npm ERR!     at evalmachine.<anonymous>:268:14
npm ERR!     at /usr/lib/nodejs/graceful-fs/graceful-fs.js:102:5
npm ERR!     at Object.oncomplete (evalmachine.<anonymous>:107:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 4.2.0-16-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g"
npm ERR! cwd /home/jim/bloc
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.4.21
npm ERR! type called_on_non_object
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/jim/bloc/npm-debug.log
npm ERR! not ok code 0

**Comment by kjameslubin** [comment]
I don't think we can do anything within `bloc` about this. I am pretty sure the problem is that the node and npm versions are old. Maybe just a warning on the README..

**Comment by jamshidh** [comment]
More trouble....

After the initial problems, I got the newest node.js and npm.  I followed what I believe was the standard route to do this

mkdir node-latest-install
cd node-latest-install/
curl http://nodejs.org/dist/node-latest.tar.gz | tar xz --strip-components=1
./configure --prefix=~/.local
make install
curl -L https://www.npmjs.com/install.sh | sh

(this was basically what I found here http://stackoverflow.com/questions/31025159/installing-nodejs-without-sudo-in-ubuntu)

then I tried to install bloc

sudo npm install -g

unfortunately, the executables for npm were all local (in .local/bin), and root didn't have access to them.  Running with full path didn't help....

~/bloc> sudo /home/jim/.local/bin/npm install -g
/usr/bin/env: node: No such file or directory


I am not sure how much of this bloc can fix, but I wanted to show you how a typical Ubuntu user will proceed when installing....

I still haven't gotten bloc installed, by the way.

**Comment by kjameslubin** [comment]
Not sure what we should do, except to make the documentation more clear and warning filled. Perhaps you can spin your experience into an FAQ? @jamshidh

**Comment by kjameslubin** [comment]
I am assigned to this but not able to reproduce the issue. Will not think about it until formal q/a starts.

**Comment by kjameslubin** [comment]
@jamshidh Can you update me on this? I can try to reproduce it on a VM or something, but I've never been able to reproduce it myself

**Comment by kjameslubin** [comment]
Ok, I think I figured out that the default version is too low, and it won't warn (which, btw, is in the `package.json`). I think it's a documentation question

**Comment by kjameslubin** [comment]
This snippet seems to work:
```
curl https://raw.githubusercontent.com/creationix/nvm/v0.25.4/install.sh | bash
source ~/.bashrc
nvm install 0.12
..
(sudo) npm install -g
```
@jamshidh Can you add it to the README as you are doing it? Going to leave this issue open

**Comment by kjameslubin** [comment]
Add to the docs - suggestion to use `nvm` Ubuntu
