### ISSUE TITLE
Error message is overly complicated....

### ISSUE THREAD

**Issue by jamshidh** [blockapps/bloc#36]
Type in an incorrect password for "bloc upload", this is what you get

--------------

> bloc upload qqqq -s
prompt: Enter password to decrypt key file:  
Unhandled rejection Error: Invalid Password
    at KeyStore.generateEncKey (/home/jim/.local/lib/node_modules/bloc/node_modules/ethlightjs/lib/keystore.js:215:13)
    at KeyStore.exportPrivateKey (/home/jim/.local/lib/node_modules/bloc/node_modules/ethlightjs/lib/keystore.js:155:21)
    at /home/jim/.local/lib/node_modules/bloc/bin/main.js:94:33
    at tryCatcher (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)

------------------

clearly you can see the correct error message in line 1, but the other stuff is unneeded and confusing for a bloc end user.

**Comment by jamshidh** [comment]
This is true for other errors, for instance, put in the wrong contract name, this is what you get

--------------

> bloc upload qqqq -s
prompt: Enter password to decrypt key file:  
Unhandled rejection Error: ENOENT: no such file or directory, open 'meta/qqqq.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at upload (/home/jim/.local/lib/node_modules/bloc/lib/upload.js:9:33)
    at /home/jim/.local/lib/node_modules/bloc/bin/main.js:95:20
    at tryCatcher (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/promise.js:507:31)
    at Promise._settlePromiseAt (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/promise.js:581:18)
    at Promise._settlePromises (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/promise.js:697:14)
    at Async._drainQueue (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/async.js:123:16)
    at Async._drainQueues (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/jim/.local/lib/node_modules/bloc/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)

----------

A simple message would be better, like "sorry, but no contract with name 'qqqq' exists"

**Comment by ryanreich** [comment]
This is the Javascript default for uncaught exceptions.  It can be
addressed by actually going through and doing `try/catch` clauses
everywhere, which will probably actually do a lot of good, but is also a
lot of work.

**Comment by jamshidh** [comment]
Maybe one root level catch that just shows the message without the backtrace would be a better default message....  In the two cases given the message seemed to have the important info, the backtrace is more for devs of bloc to find the error and fix it.

**Comment by kjameslubin** [comment]
Most of these "emanate" from `blockapps-js`. Assigning @ryanreich
