### ISSUE TITLE
-s parameter should not have to be in specific order

### ISSUE THREAD

**Issue by kejace** [blockapps/bloc#39]
Here's my attempt at uploading a contract. I couldn't remember the particular order of `-s` and reading the error message made me think that it was `.sol` that I had forgotten to add. Once I tried `-s` in the right order I still got an error because of the addition of `.sol`. I think making `bloc` order agnostic with respect to flags would have prevented this.

```
C:\haskell\bloc\myapp>bloc upload -s Ponzi
contract name required

C:\haskell\bloc\myapp>bloc upload -s Ponzi.sol
contract name required

C:\haskell\bloc\myapp>bloc upload Ponzi.sol -s
prompt: Enter password to decrypt key file:
Unhandled rejection Error: ENOENT: no such file or directory, open 'C:\haskell\bloc\myapp\meta\Ponzi.sol.json'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at upload (C:\r\npm\node_modules\bloc\lib\upload.js:9:33)
    at C:\r\npm\node_modules\bloc\bin\main.js:95:20
    at tryCatcher (C:\r\npm\node_modules\bloc\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (C:\r\npm\node_modules\bloc\node_modules\bluebird\js\main\promise.js:507:31)
    at Promise._settlePromiseAt (C:\r\npm\node_modules\bloc\node_modules\bluebird\js\main\promise.js:581:18)
    at Promise._settlePromises (C:\r\npm\node_modules\bloc\node_modules\bluebird\js\main\promise.js:697:14)
    at Async._drainQueue (C:\r\npm\node_modules\bloc\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (C:\r\npm\node_modules\bloc\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\r\npm\node_modules\bloc\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:368:17)
```

**Comment by kjameslubin** [comment]
yes, agreed. This particular case seems like an easy fix but the general case is a bit trickier ..

**Comment by kejace** [comment]
Agreed. Probably long term solution is to use a command line parser library.

**Comment by kjameslubin** [comment]
We do... It's just that command (bloc <dosomething>) and flags (bloc dosomething --flag) are different. The flags come back as an object, and the commands as an array, I thin.
