### ISSUE TITLE
'bloc init' throws module error

### ISSUE THREAD

**Issue by ryannyunn** [blockapps/bloc#70]
After following through with the installation process, typing this into terminal:
```
bloc init
```
throws this error:
```
module.js:340
    throw err;
    ^

Error: Cannot find module 'browserify-sha3'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ryanyun/Desktop/bloc/node_modules/ethereumjs-util/index.js:1:76)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/ryanyun/Desktop/bloc/node_modules/ethereumjs-tx/index.js:1:79)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
```

**Comment by kjameslubin** [comment]
I've never been able to reproduce this but I believe others have fixed it by `npm install -g browerify-sha3`. Will work on a fix

**Comment by ryannyunn** [comment]
Hi @kjameslubin, thanks for getting back so quickly!

Just tried that and I got this error:
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/Cellar/node/5.1.0/bin/node" "/usr/local/bin/npm" "install" "-g" "browerify-sha3"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/browerify-sha3
npm ERR! 404 
npm ERR! 404 'browerify-sha3' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ryanyun/Desktop/bloc/npm-debug.log
```

**Comment by kjameslubin** [comment]
Hmm... It looks like it is there:
https://www.npmjs.com/package/browserify-sha3

**Comment by kjameslubin** [comment]
Ah, I missed spelled `browserify`

**Comment by ryannyunn** [comment]
Ah! It is working now - thank you so much @kjameslubin!
